# Generated by Django 4.2 on 2025-01-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('P', 'Planta'), ('E', 'Electrico'), ('F', 'Fuego'), ('T', 'Tierra')], max_length=30),
        ),
    ]
