# Generated by Django 4.2 on 2025-01-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('F', 'Fuego'), ('T', 'Tierra'), ('E', 'Electrico'), ('A', 'Agua')], max_length=30),
        ),
    ]
