# Generated by Django 4.2 on 2025-01-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='trainer',
            new_name='Trainer',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(default='pokemon_images', upload_to='pokemon_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('P', 'Planta'), ('E', 'Electrico'), ('A', 'Agua'), ('T', 'Tierra')], max_length=30),
        ),
    ]
