# Generated by Django 4.2 on 2025-01-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='Trainer',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('F', 'Fuego'), ('A', 'Agua'), ('T', 'Tierra'), ('E', 'Electrico')], max_length=30),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
    ]
