# Generated by Django 4.2 on 2025-01-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_remove_pokemon_trainer_alter_pokemon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('T', 'Tierra'), ('E', 'Electrico'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
